general:
  tmdb_api_key: "1501ee8a1e2f68bd09aeeace5f466acf"
  igdb_client_id: "lhjnjn7iiyeyqoons4uv7n7zu0isbx"
  igdb_bearer_token: "4pc5wo4oqqcntcmxa5bi3j11mjoaix"

paths:
  torrent_dir: "/mnt/c/Users/ashou/GitHub/seed-tools/torrents"
  screenshots_dir: "/mnt/c/Users/ashou/GitHub/seed-tools/screenshots"
  ffmpeg: "/mnt/c/Users/ashou/GitHub/seed-tools/bin/ffmpeg"
  ffprobe: "/mnt/c/Users/ashou/GitHub/seed-tools/bin/ffprobe"
  mkbrr: "/mnt/c/Users/ashou/GitHub/seed-tools/bin/mkbrr"
  mediainfo: "/mnt/c/Users/ashou/GitHub/seed-tools/bin/mediainfo"

qbittorrent:
  - webui_url: "http://32.216.136.243:8080"
    username: "thc"
    password: "259242"
    category: "TV"
    default_save_path: "/home/thc/downloads"
    executable: ""
    fastresumes: "/home/thc/.local/share/qBittorrent/BT_backup"

  - webui_url: ""
    username: ""
    password: ""
    category: ""
    default_save_path: ""
    executable: ""
    fastresumes: ""

deluge:
    webui_url: ""
    daemon_port: 24537
    username: ""
    password: ""
    label: ""
    default_save_path: ""
