general:
  tmdb_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  igdb_client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  igdb_bearer_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

paths:
  torrent_dir: "/home/user/seed-tools/torrents"
  screenshots_dir: "/home/user/seed-tools/screenshots"
  ffmpeg: "/home/user/seed-tools/bin/ffmpeg"
  ffprobe: "/home/user/seed-tools/bin/ffprobe"
  mkbrr: "/home/user/seed-tools/bin/mkbrr"
  mediainfo: "/home/user/seed-tools/bin/mediainfo"

qbittorrent:
  - webui_url: "http://localhost:21540"
    username: "user"
    password: "xxxxxxxxxxxxxxxxxxxxxxx"
    category: ""
    default_save_path: "/home/user/files"
    executable: "/usr/bin/qbittorrent-nox"
    fastresumes: "/home/user/.local/share/qBittorrent/BT_backup"

  - webui_url: "http://localhost:36518"
    username: "xxxxxx"
    password: "xxxxxxxxxxxxxxxxx"
    category: ""
    default_save_path: "/home/user/files"
    executable: "/usr/bin/qbittorrent-nox"
    fastresumes: "/home/user/.local/share/qBittorrent/BT_backup"

deluge:
    webui_url: "https://deluge.fastpanther.box.ca"
    daemon_port: 19148
    username: "user"
    password: "xxxxxxxxxxxxxxxxx"
    label: ""
    default_save_path: "/home/user/files"

imgbb:
  imgbb_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"