general:
  tmdb_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxx"

paths:
  torrent_dir: "/home/user/seed-tools/torrents"
  screenshots_dir: "/home/user/seed-tools/screenshots"
  ffmpeg: "/home/user/seed-tools/bin/ffmpeg"
  ffprobe: "/home/user/seed-tools/bin/ffprobe"
  mkbrr: "/home/user/seed-tools/bin/mkbrr"

qbittorrent:
  - webui_url: "http://localhost:8080"
    username: "user"
    password: "xxxxxxxxxxxxx"
    category: ""
    default_save_path: "/home/user/files"
    executable: "/usr/bin/qbittorrent-nox"
    fastresumes: "/home/user/.local/share/qBittorrent/BT_backup"


  - webui_url: "http://localhost:8081"
    username: "user"
    password: "xxxxxxxxxxxxxx"
    category: ""
    default_save_path: "/home/user/files"
    executable: "/usr/bin/qbittorrent-nox"
    fastresumes: "/home/user/.local/share/qBittorrent/BT_backup"

deluge:
    webui_url: "https://localhost:52345"
    daemon_port: 19148
    username: "user"
    password: "xxxxxxxxxxxxxxxxxxxxx"
    label: ""
    default_save_path: "/home/user/files"    